apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
	
	path('', views.Listar_Noticias, name = 'listar'),

	path('Detalle/<int:pk>', views.Detalle_Noticias, name = 'detalle'),
	
	path('Comentario/', views.Comentar_Noticia, name = 'comentar'),
    
    path('Comentario/eliminar/<int:pk>', views.eliminar_comentario, name = 'eliminar_comentario'),
    
	path('Comentario/editar/<int:pk>', views.modificar_comentario, name = 'modificar_comentario')
	
]

apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    
    path('registro/', views.Registro.as_view(), name = 'registro'),

   

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#URL LOGIN
from django.contrib.auth import views as auth

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    # 1 PARAMETROS ES EL TEXTO DE LA URL
    # 2 LA VISTA QUE VA EJECUTAR
    # 3 ES EL NOMBRE LA URL (aun no lo usamos)
    path('', views.Home, name = 'home'),
    #No necesariamente estos 3 valores (parametors) se deben llamar igual
    path('Nosotros/', views.Nosotros, name = 'nosotros'),

    #LOGIN
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    # URL DE APLICACION
    path('Noticias/', include('apps.noticias.urls')),
    path('Usuario/',include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario

class Categoria(models.Model):
	nombre = models.CharField(max_length = 60)

	def __str__(self):
		return self.nombre

class Noticia(models.Model):
	id = models.AutoField(primary_key=True)
	titulo = models.CharField(max_length = 150)
	cuerpo = models.TextField()
	imagen = models.ImageField(upload_to = 'noticias')
	categoria_noticia = models.ForeignKey(Categoria, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.titulo

class Comentario(models.Model):
	id = models.AutoField(primary_key=True)
	usuario = models.ForeignKey(Usuario, on_delete = models.CASCADE)
	texto = models.TextField(max_length = 1500)
	noticia = models.ForeignKey(Noticia, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{noticia}->{texto}"

apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
	pass

apps/usuarios/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class RegistroForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={
        "type":"email",
        "required": "true"
    }), label="Email")
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        "type":"text",
        "required": "true"
    }), label="Nombre")
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        "type":"text",
        "required": "true"
    }), label="Apellido")
    username =forms.CharField(widget=forms.TextInput(attrs={
        "type":"text",
        "required": "true"
    }), label="Usuario")
    password1 = forms.CharField(widget=forms.TextInput(attrs={
        "type":"password",
        "required": "true"
    }), label="Contraseña")
    password2 = forms.CharField(widget=forms.TextInput(attrs={
        "type":"password",
        "required": "true"
    }), label="Confirmar-Contraseña")

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

apps/noticias/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required, user_passes_test, permission_required

from .models import Noticia, Categoria, Comentario

from django.urls import reverse_lazy

def Listar_Noticias(request):
    contexto = {}

    id_categoria = request.GET.get('id', None)
    orden_asc = request.GET.get('orden_asc', None)
    orden_desc = request.GET.get('orden_desc', None)
    fecha_asc = request.GET.get('fecha_asc', None)
    fecha_desc = request.GET.get('fecha_desc', None)

    if id_categoria:
        noticias = Noticia.objects.filter(categoria_noticia=id_categoria)
    else:
        noticias = Noticia.objects.all()

    # Ordenar alfabéticamente asc si se proporciona el parámetro "orden"
    if orden_asc == 'alfabetico':
        noticias = noticias.order_by('titulo')  # Asume que el campo de título es 'titulo'
        
	# Ordenar alfabéticamente descendentemente
    if orden_desc == 'alfabetico':
        noticias = noticias.order_by('-titulo')  # El guion antes de 'titulo' indica orden
    
	# Ordenar por fecha ascendentemente
    if fecha_asc == 'fecha':
        noticias = noticias.order_by('fecha')  # El guion antes de 'titulo' indica orden 
	# Ordenar por fecha descendentemente
    if fecha_desc == 'fecha':
        noticias = noticias.order_by('-fecha')  # El guion antes de 'titulo' indica orden
    
    contexto['noticias'] = noticias

    categorias = Categoria.objects.all().order_by('nombre')
    contexto['categorias'] = categorias

    return render(request, 'noticias/listar.html', contexto)



def Detalle_Noticias(request, pk):
	contexto = {}

	n = Noticia.objects.get(pk = pk) #RETORNA SOLO UN OBEJTO
	contexto['noticia'] = n

	c = Comentario.objects.filter(noticia = n)
	contexto['comentarios'] = c

	return render(request, 'noticias/detalle.html',contexto)


@login_required
def Comentar_Noticia(request):

	com = request.POST.get('comentario',None)
	usu = request.user
	noti = request.POST.get('id_noticia', None)# OBTENGO LA PK
	noticia = Noticia.objects.get(pk = noti) #BUSCO LA NOTICIA CON ESA PK
	coment = Comentario.objects.create(usuario = usu, noticia = noticia, texto = com)

	return redirect(reverse_lazy('noticias:detalle', kwargs={'pk': noti}))

@login_required
def eliminar_comentario(request, pk):
     com = Comentario.objects.get(pk = pk)
     com.delete()
     return redirect(reverse_lazy('noticias:detalle', kwargs={'pk': com.noticia.id}))

@login_required
def modificar_comentario(request, pk):
    comentario=request.POST.get('comentarioedit', None)
    com = Comentario.objects.get(pk = pk)
    com.texto = comentario
    com.save()
    return redirect(reverse_lazy('noticias:detalle', kwargs={'pk': com.noticia.id}))



#{'nombre':'name', 'apellido':'last name', 'edad':23}
#EN EL TEMPLATE SE RECIBE UNA VARIABLE SEPARADA POR CADA CLAVE VALOR
# nombre
# apellido
# edad

'''
ORM

CLASE.objects.get(pk = ____)
CLASE.objects.filter(campos = ____)
CLASE.objects.all() ---> SELECT * FROM CLASE

'''

apps/usuarios/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import RegistroForm
# Create your views here.

class Registro(CreateView):
	#FORMULARIO DJANGO
	form_class = RegistroForm
	success_url = reverse_lazy('login')
	template_name = 'usuarios/registro.html'

blog/views.py
from django.shortcuts import render

#request 'es un diccionario que continuamente se va pasando entre el navegador y el servidor'

def Home(request):

	return render(request, 't_home.html')


def Nosotros(request):

	return render(request, 't_nosotros.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>GRUPO Z{% block titulo %}{% endblock titulo %}</title>
	<link rel="shortcut icon" href="{% static 'img/5712418.ico' %}">
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
	<link rel="stylesheet" href="https://codepen.io/jsulpis/pen/ExdxLgM.scss">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/botones.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/nosotros.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/detalle-noticia.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/comentarios.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
</head>
<body>
	<section class="photo" id="inicio">
  
		<div class="nav" id="sticker">
		<label for="toggle">&#9776</label>
		<input type="checkbox" id="toggle" />
		<div class="menu">
		  <h5 class="logo"><img src="{% static 'img/logo-sf.png' %}" width="70px" height="70px" ></h5>
		  <a href="{% url 'home' %}">INICIO</a>
		  <a href="{% url 'noticias:listar' %}">NOTICIAS</a>
		  <a href="{% url 'nosotros' %}">NOSOTROS</a>
		  {% if user.is_authenticated %}
		  	<a class="nombre">Hola, {{ user.username }}</a>
		  	<a href="{% url 'logout' %}">CERRAR SESIÓN</a>
		  {% else %}
			<a href="{% url 'login' %}">INICIAR SESIÓN</a>
			<a href="{% url 'usuarios:registro' %}">REGISTRARSE</a>
		  {% endif %}
		</div>
	  </div>
	  <div class="photo-text">
		<h4 data-ix="skype">INFORMATORIO</h4>
		<p data-ix="subtitle-hero-up">GRUPO Z</p>
		  </div>
		<div class="overlay"></div>
	</section>
	<div class="fondo">
		{% block contenido %}
								
		{% endblock contenido %}
	</div>
	<footer>
		<div class="bottom-bar">
			TODOS LOS DERECHOS RESERVADOS © 2023 | <a href="">GRUPO Z</a> | <a href="">TÉRMINOS Y SERVICIOS</a>
		</div>
	  </footer>
	<!--DEFINO FUNCION MOSTRAR BOTON-->
	<script type="text/javascript" src="{% static 'js/botones.js' %}"></script>
	<!--DEFINO FUNCION MOSTRAR BOTON-->
	<script type="text/javascript" src="{% static 'js/mover-mouse.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://daks2k3a4ib2z.cloudfront.net/588509aba93e9ed75d02ed68/js/knife-fox-playground.7c3e6668d.js"></script>
	<script src="https://fractalhost.com/landing1/js/jquery.sticky.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
	<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} - NOTICIAS{% endblock titulo %}


{% block contenido %}
	<div class="content">
		<div class="grand-title" id="servicio">
		<h4 data-ix="slowfade-scroll-bigs">NOTICIAS</h4>
		</div>
	</div>
	<main>
	<article class="movie-card">
		<img class="imagen-noticia" src="{{noticia.imagen.url}}" />

		<div class="contenido">
		  <h1>{{noticia.titulo}}</h1>

		  <div class="infos">
			<span>·&nbsp;&nbsp;{{noticia.categoria_noticia}}&nbsp;&nbsp;·&nbsp;&nbsp;{{noticia.fecha}}&nbsp;&nbsp;·</span>
		  </div>
		</div>
	  </article>
	  <br>
	  <br>
	  <div class="cuerpo-noticia">
		<pre>{{noticia.cuerpo}}</pre>
	</div>
	<br><br>
	<div class="linea-separadora"></div>
	<div class="comentarios">
		<h3 class="comment-titulo">COMENTARIOS</h3>
		<div class="caja-comentario">
			<form method="POST" action="{% url 'noticias:comentar' %}" >{% csrf_token %}
				<textarea name="comentario" maxlength="1500" placeholder="Escribe tu comentario.."> </textarea>
				<input type="text" name="id_noticia" value="{{noticia.pk}}" hidden="">
				<button type="submit" class="btn-guardar">GUARDAR</button>
			</form>
		</div>
	</div>
	<!-- Contenedor Principal -->
	<div class="comments-container">

		<ul id="comments-list" class="comments-list">
			{% for com in comentarios %}
			<li>
				<div class="comment-main-level">
					<div class="comment-box">
						<div class="comment-head">
							<h6 class="comment-name by-author"><a>{{com.usuario}}</a></h6>
							<span>{{com.fecha}}</span>
							{% if user == com.usuario or user.pk == 2%}
							<a class="icono" href="{% url 'noticias:eliminar_comentario' com.id %}" onclick='guardarPosicionDesplazamiento();'><i class="fa fa-trash"></com></i></a>
							<a class="icono" onclick='guardarPosicionDesplazamiento(); mostrarEdit("com{{com.id}}");'><i class=" fa fa-pencil" ></com></i></a>
							{% endif %}
						</div>
						<div class="comment-content">
							{{com.texto}}
						</div>
						<div class="caja-comentario" id="com{{com.id}}" style="display: none;">
								<form method="POST" action="{% url 'noticias:modificar_comentario' com.id %}" >{% csrf_token %}
									<textarea name="comentarioedit" maxlength="1500" placeholder="Escribe tu comentario..">{{com.texto}}</textarea>
									<input type="text" name="id_noticia" value="{{noticia.pk}}" hidden="">
									<button type="submit" class="btn-guardar">EDITAR</button>
								</form>
						</div>
					</div>
				</div>
			</li>
			{% endfor %}
		</ul>
	</div>
	</main>

{% endblock contenido %}

templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} - NOTICIAS{% endblock titulo %}


{% block contenido %}
	<div class="content">
		<div class="grand-title" id="servicio">
		  <h4 data-ix="slowfade-scroll-bigs">NOTICIAS</h4>
		</div>
	</div>
		<!-----------------------FILTRADO------------------------------>
		<div class="filtrar">
			<div class="filtrar-cat">
				<div class="caja-botones">
					<a  id="boton" onclick="mostrarCat();" >
						<span></span>
						<span></span>
						<span></span>
						<span></span>
						FILTRAR POR CATEGORÍAS
					</a>
					<a  id="boton" onclick="mostrarAlf();">
						<span></span>
						<span></span>
						<span></span>
						<span></span>
						FILTRAR ALFÁBETICAMENTE
					</a>
					<a  id="boton" onclick="mostrarFec();">
						<span></span>
						<span></span>
						<span></span>
						<span></span>
						FILTRAR POR FECHA
					</a>
					<div id="cat-ocultas">
						<a  href="{% url 'noticias:listar' %}" onclick="guardarPosicionDesplazamiento();">TODAS</a>
						{% for cat in categorias %}
						<a  href="?id={{cat.pk}}">{{cat.nombre}}</a>
						{% endfor %}
						<a  id="boton2" onclick="ocultarCat();">OCULTAR FILTROS</a>
					</div>
					<div id="alf-ocultas">
						<a  href="?id={{cat.pk}}&orden_asc=alfabetico">ORDEN A-Z</a>
						<a  href="?id={{cat.pk}}&orden_desc=alfabetico">ORDEN Z-A</a>
						<a  id="boton2" onclick="ocultarAlf();">OCULTAR FILTROS</a>
					</div>
					<div id="fechas-ocultas">
						<a  href="?id={{cat.pk}}&fecha_asc=fecha">FECHA ASC</a>
						<a  href="?id={{cat.pk}}&fecha_desc=fecha">FECHA DESC</a>
						<a  id="boton2" onclick="ocultarFec();">OCULTAR FILTROS</a>
					</div>
				</div>
			</div>
		</div>


	<section class="game-section">
		<div class="owl-carousel custom-carousel owl-theme">
		{% for noti in noticias %}
		  <div class="item" style="background-image: url({{noti.imagen.url}});">
			<div class="item-desc">
				<h1><a class="" href="{% url 'noticias:detalle' noti.pk %}">{{noti.titulo}}</a></h1>
			</div>
		  </div>
		{% endfor %}
		</div>
	</section>

{% endblock contenido %}

templates/t_home.html
{% extends 'base.html' %}
{% load static %}

templates/t_nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} - NOSOTROS{% endblock titulo %}


{% block contenido %}
<div class="content">
	<div class="grand-title" id="servicio">
	  <h4 data-ix="slowfade-scroll-bigs">NOSOTROS</h4>
	</div>
</div>
<main>
	<div class="historia">
		<h3>Nuestra Historia </h3>
		<p>GRUPO Z nace en 2023, cuando un grupo de estudiantes apasionados por la 
			tecnología decidió dar vida a un proyecto que explorara de manera accesible y comprensible la inteligencia artificial. Desde entonces, hemos evolucionado como una plataforma comprometida con la divulgación de conocimientos y perspectivas sobre este campo en constante cambio.
			En nuestros primeros días, nos enfrentamos a los desafíos típicos de cualquier inicio, pero con determinación y una visión clara, 
			GRUPO Z comenzó a tomar forma. Aprendimos valiosas lecciones sobre la complejidad y el potencial de la inteligencia 
			artificial, y nos embarcamos en la misión de compartir esos conocimientos de manera que sea accesible para todos.</p>
	</div>
	<div class="equipo">
		<h3>Equipo</h3>
		<ul > <a class=" fa fa-user-o"></a> Leandro Zacariaz
			<li > <a class=" fa fa-angle-double-right"></a> 23 años</li>
			<li > <a class=" fa fa-map-marker"></a> Quitilipi, Chaco</li>
			<li> <a class=" fa fa-book"></a> Estudiante de Ingeniería en Sistemas de la Información - UNCAus</li>
			<li> <a href="https://github.com/LeandroZacariaz" class=" fa fa-github"> github.com/LeandroZacariaz </a></li>
		</ul>
		<ul> <a class=" fa fa-user-o"></a> Guillermo Ferreira
			<li > <a class=" fa fa-angle-double-right"></a> 23 años</li>
			<li > <a class=" fa fa-map-marker"></a> Quitilipi, Chaco</li>
			<li> <a class=" fa fa-book"></a> Estudiante de Ingeniería en Sistemas de la Información - UNCAus</li>
			<li> <a href="https://github.com/guishe-art" class=" fa fa-github"> github.com/guishe-art </a></li>
		</ul>
		<ul> <a class=" fa fa-user-o"></a> Maximiliano Milesi
			<li > <a class=" fa fa-angle-double-right"></a> 23 años</li>
			<li > <a class=" fa fa-map-marker"></a> Quitilipi, Chaco</li>
			<li> <a class=" fa fa-book"></a> Estudiante de Ingeniería en Sistemas de la Información - UNCAus</li>
			<li> <a href="https://github.com/Mqqqxi" class=" fa fa-github"> github.com/Mqqqxi </a></li>
		</ul>
		<ul><a class=" fa fa-user-o"></a> Jose Avila
			<li >  <a class=" fa fa-angle-double-right"></a>  28 años</li>
			<li > <a class=" fa fa-map-marker"></a> Goya, Corrientes</li>
			<li> <a class=" fa fa-book"></a> Estudiante de Ingeniería en Sistemas de la Información - UNCAus</li>
			<li> <a href="https://github.com/Jose-L-Avila" class=" fa fa-github"> github.com/Jose-L-Avila </a></li>
		</ul>
	</div>
	<div class="contacto">
		<h3>Contacto</h3>
		<ul>
			<li> <a href="https://instagram.com" class="fa fa-instagram"></a></li>
			<li> <a href="https://x.com" class="fa fa-twitter"></a></li>
			<li> <a href="https://github.com" class="fa fa-github"></a></li>
			<li> <a href="https://facebook.com" class="fa fa-facebook-official"></a></li>
			<li> <a href="https://gmail.com" class="fa fa-google"></a></li>
		</ul>
	</div>
</main>
{% endblock contenido %}

templates/usuarios/login.html
{% extends 'base.html' %}

{% block contenido %}
<div class="content">
	<div class="grand-title" id="servicio">
	  <h4 data-ix="slowfade-scroll-bigs">INICIAR SESIÓN</h4>
	</div>
  </div>
	<main>
			<div class="login-box">
				<h2>Iniciar sesión</h2>
				<form method="POST">{%csrf_token%}
					{{form.errors}}
				<div class="user-box">
					<input type="text" name="username" required="">
					<div class="label-div">Usuario</div>
				</div>
				<div class="user-box">
					<input type="password" name="password" required="">
					<div class="label-div">Contraseña</div>
				</div>
				<a>
					<span></span>
					<span></span>
					<span></span>
					<span></span>
					<button type="submit" class="btn-login">Iniciar sesión</button>
				</a>
				</form>
				<a href="{% url 'usuarios:registro' %}">
					<span></span>
					<span></span>
					<span></span>
					<span></span>
					<button class="btn-login">Registrarse</button>
				</a>
				
			</div>
		</main>
{% endblock %}

templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Registroa{% endblock %}
{% block contenido %}

      <div class="content">
        <div class="grand-title" id="servicio">
          <h4 data-ix="slowfade-scroll-bigs">REGISTRARSE</h4>
        </div>
      </div>
        <main>
          <div class="login-box">
            <h2>Registrarse</h2>
            <form method="POST">{%csrf_token%}
            <div class="user-box">
              {{ form.first_name }}
              <div class="label-div">Nombre/s</div>
            </div>
            <div class="user-box">
              {{ form.last_name }}
              <div class="label-div">Apellido/s</div>
            </div>
            <div class="user-box">
              {{ form.username }}
              <div class="label-div">Usuario</div>
            </div>
            <div class="user-box">
              {{ form.email }}
              <div class="label-div">Correo electrónico</div>
            </div>
            <div class="user-box">
              {{ form.password1 }}
              <div class="label-div">Contraseña</div>
            </div>
            <div class="user-box">
              {{ form.password2 }}
              <div class="label-div">Confirmar contraseña</div>
            </div>
            <a>
              <span></span>
              <span></span>
              <span></span>
              <span></span>
              <button type="submit" class="btn-login">Registrarse</button>
            </a>
            </form>
          </div>
        </main>
{% endblock %}